[2022-09-05T21:10:03.978+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05T21:10:04.006+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05T21:10:04.007+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:10:04.007+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 6
[2022-09-05T21:10:04.007+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:10:04.032+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2022-09-01 00:00:00+00:00
[2022-09-05T21:10:04.041+0000] {standard_task_runner.py:52} INFO - Started process 12042 to run task
[2022-09-05T21:10:04.046+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'delete_data_from_table', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '414', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmpd_ipl892', '--error-file', '/tmp/tmpoo7l20rd']
[2022-09-05T21:10:04.047+0000] {standard_task_runner.py:80} INFO - Job 414: Subtask delete_data_from_table
[2022-09-05T21:10:04.201+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.delete_data_from_table scheduled__2022-09-01T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T21:10:04.368+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=delete_data_from_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-09-05T21:10:04.386+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T21:10:04.393+0000] {sql.py:315} INFO - Running statement: delete from dag_runs where dt =  '2022-09-01' and dag_id = 'dag_with_postgres_operator_v03', parameters: None
[2022-09-05T21:10:04.395+0000] {sql.py:324} INFO - Rows affected: 0
[2022-09-05T21:10:04.434+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=delete_data_from_table, execution_date=20220901T000000, start_date=20220905T211003, end_date=20220905T211004
[2022-09-05T21:10:04.511+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T21:10:04.613+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
