[2022-09-05T21:10:05.944+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-09-03T00:00:00+00:00 [queued]>
[2022-09-05T21:10:05.974+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-09-03T00:00:00+00:00 [queued]>
[2022-09-05T21:10:05.975+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:10:05.975+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-05T21:10:05.975+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:10:06.004+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2022-09-03 00:00:00+00:00
[2022-09-05T21:10:06.012+0000] {standard_task_runner.py:52} INFO - Started process 12051 to run task
[2022-09-05T21:10:06.016+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2022-09-03T00:00:00+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmppmsx7aom', '--error-file', '/tmp/tmpwq5wchy6']
[2022-09-05T21:10:06.017+0000] {standard_task_runner.py:80} INFO - Job 421: Subtask insert_into_table
[2022-09-05T21:10:06.177+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2022-09-03T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T21:10:06.302+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=insert_into_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-03T00:00:00+00:00
[2022-09-05T21:10:06.320+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T21:10:06.326+0000] {sql.py:315} INFO - Running statement: insert into dag_runs (dt, dag_id) values ('2022-09-03', 'dag_with_postgres_operator_v03'), parameters: None
[2022-09-05T21:10:06.327+0000] {sql.py:324} INFO - Rows affected: 1
[2022-09-05T21:10:06.358+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=insert_into_table, execution_date=20220903T000000, start_date=20220905T211005, end_date=20220905T211006
[2022-09-05T21:10:06.398+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T21:10:06.474+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
