[2022-09-06T15:07:53.222+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-05T00:00:00+00:00 [queued]>
[2022-09-06T15:07:53.249+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-05T00:00:00+00:00 [queued]>
[2022-09-06T15:07:53.250+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:07:53.250+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T15:07:53.250+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:07:53.283+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-05 00:00:00+00:00
[2022-09-06T15:07:53.290+0000] {standard_task_runner.py:52} INFO - Started process 1071 to run task
[2022-09-06T15:07:53.294+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'postgres_to_s3', 'scheduled__2022-05-05T00:00:00+00:00', '--job-id', '580', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmp6pj10b_e', '--error-file', '/tmp/tmp6bh8bil3']
[2022-09-06T15:07:53.295+0000] {standard_task_runner.py:80} INFO - Job 580: Subtask postgres_to_s3
[2022-09-06T15:07:53.416+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-05T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T15:07:53.551+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v02
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-05T00:00:00+00:00
[2022-09-06T15:07:54.379+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-06T15:07:54.402+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T15:07:54.417+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 23, in postgres_to_s3
    (ds_nodash,next_ds_nodash))
psycopg2.errors.UndefinedColumn: column "dat" does not exist
LINE 1: select * from orders where date >= '20220505' and dat < '202...
                                                          ^
HINT:  Perhaps you meant to reference the column "orders.date".

[2022-09-06T15:07:54.442+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v02, task_id=postgres_to_s3, execution_date=20220505T000000, start_date=20220906T150753, end_date=20220906T150754
[2022-09-06T15:07:54.858+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 580 for task postgres_to_s3 (column "dat" does not exist
LINE 1: select * from orders where date >= '20220505' and dat < '202...
                                                          ^
HINT:  Perhaps you meant to reference the column "orders.date".
; 1071)
[2022-09-06T15:07:54.975+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-06T15:07:55.128+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-06T15:09:08.139+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-05T00:00:00+00:00 [queued]>
[2022-09-06T15:09:08.154+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-05T00:00:00+00:00 [queued]>
[2022-09-06T15:09:08.154+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:09:08.155+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T15:09:08.155+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:09:08.175+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-05 00:00:00+00:00
[2022-09-06T15:09:08.180+0000] {standard_task_runner.py:52} INFO - Started process 1155 to run task
[2022-09-06T15:09:08.183+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'postgres_to_s3', 'scheduled__2022-05-05T00:00:00+00:00', '--job-id', '596', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpo4y8rp9d', '--error-file', '/tmp/tmpexpamgd3']
[2022-09-06T15:09:08.185+0000] {standard_task_runner.py:80} INFO - Job 596: Subtask postgres_to_s3
[2022-09-06T15:09:08.271+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-05T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T15:09:08.372+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v02
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-05T00:00:00+00:00
[2022-09-06T15:09:08.373+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-06T15:09:08.386+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T15:09:08.392+0000] {dag_with_postgres_hooks.py:30} INFO - save orders data in text file dags/get_orders_20220505.txt
[2022-09-06T15:09:08.393+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06T15:09:08.410+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v02, task_id=postgres_to_s3, execution_date=20220505T000000, start_date=20220906T150908, end_date=20220906T150908
[2022-09-06T15:09:08.440+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T15:09:08.482+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
