[2022-09-06T15:07:52.573+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-02T00:00:00+00:00 [queued]>
[2022-09-06T15:07:52.601+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-02T00:00:00+00:00 [queued]>
[2022-09-06T15:07:52.601+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:07:52.601+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T15:07:52.601+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:07:52.627+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-02 00:00:00+00:00
[2022-09-06T15:07:52.638+0000] {standard_task_runner.py:52} INFO - Started process 1066 to run task
[2022-09-06T15:07:52.646+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'postgres_to_s3', 'scheduled__2022-05-02T00:00:00+00:00', '--job-id', '577', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpwwjqwx7a', '--error-file', '/tmp/tmpmd9xzj0g']
[2022-09-06T15:07:52.648+0000] {standard_task_runner.py:80} INFO - Job 577: Subtask postgres_to_s3
[2022-09-06T15:07:52.784+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-02T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T15:07:52.959+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v02
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-02T00:00:00+00:00
[2022-09-06T15:07:53.372+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-06T15:07:54.476+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T15:07:55.761+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 23, in postgres_to_s3
    (ds_nodash,next_ds_nodash))
psycopg2.errors.UndefinedColumn: column "dat" does not exist
LINE 1: select * from orders where date >= '20220502' and dat < '202...
                                                          ^
HINT:  Perhaps you meant to reference the column "orders.date".

[2022-09-06T15:07:56.067+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v02, task_id=postgres_to_s3, execution_date=20220502T000000, start_date=20220906T150752, end_date=20220906T150756
[2022-09-06T15:07:56.288+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 577 for task postgres_to_s3 (column "dat" does not exist
LINE 1: select * from orders where date >= '20220502' and dat < '202...
                                                          ^
HINT:  Perhaps you meant to reference the column "orders.date".
; 1066)
[2022-09-06T15:07:56.333+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-06T15:07:56.469+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-06T15:09:07.430+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-02T00:00:00+00:00 [queued]>
[2022-09-06T15:09:07.447+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-02T00:00:00+00:00 [queued]>
[2022-09-06T15:09:07.448+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:09:07.448+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T15:09:07.448+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:09:07.470+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-02 00:00:00+00:00
[2022-09-06T15:09:07.476+0000] {standard_task_runner.py:52} INFO - Started process 1151 to run task
[2022-09-06T15:09:07.481+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'postgres_to_s3', 'scheduled__2022-05-02T00:00:00+00:00', '--job-id', '593', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpyc3xavv9', '--error-file', '/tmp/tmpcdec9b8c']
[2022-09-06T15:09:07.482+0000] {standard_task_runner.py:80} INFO - Job 593: Subtask postgres_to_s3
[2022-09-06T15:09:07.614+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-02T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T15:09:07.792+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v02
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-02T00:00:00+00:00
[2022-09-06T15:09:07.795+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-06T15:09:07.816+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T15:09:07.828+0000] {dag_with_postgres_hooks.py:30} INFO - save orders data in text file dags/get_orders_20220502.txt
[2022-09-06T15:09:07.829+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06T15:09:07.855+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v02, task_id=postgres_to_s3, execution_date=20220502T000000, start_date=20220906T150907, end_date=20220906T150907
[2022-09-06T15:09:07.902+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T15:09:07.962+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
