[2022-09-05T21:00:58.383+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05T21:00:58.406+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05T21:00:58.407+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:00:58.407+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-05T21:00:58.407+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:00:58.444+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-09-04 00:00:00+00:00
[2022-09-05T21:00:58.452+0000] {standard_task_runner.py:52} INFO - Started process 11598 to run task
[2022-09-05T21:00:58.455+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v02', 'create_postgres_table', 'scheduled__2022-09-04T00:00:00+00:00', '--job-id', '396', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmpmhae7ybq', '--error-file', '/tmp/tmpb_of0elj']
[2022-09-05T21:00:58.456+0000] {standard_task_runner.py:80} INFO - Job 396: Subtask create_postgres_table
[2022-09-05T21:00:58.666+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v02.create_postgres_table scheduled__2022-09-04T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T21:00:58.931+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v02
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05T21:00:58.947+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T21:00:58.954+0000] {sql.py:315} INFO - Running statement: create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            ), parameters: None
[2022-09-05T21:00:58.956+0000] {postgres.py:94} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-09-05T21:00:59.174+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v02, task_id=create_postgres_table, execution_date=20220904T000000, start_date=20220905T210058, end_date=20220905T210059
[2022-09-05T21:00:59.211+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T21:00:59.395+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
