[2022-09-06T15:07:52.843+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-03T00:00:00+00:00 [queued]>
[2022-09-06T15:07:52.870+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-03T00:00:00+00:00 [queued]>
[2022-09-06T15:07:52.871+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:07:52.871+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T15:07:52.871+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:07:52.922+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-03 00:00:00+00:00
[2022-09-06T15:07:52.932+0000] {standard_task_runner.py:52} INFO - Started process 1068 to run task
[2022-09-06T15:07:52.938+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'postgres_to_s3', 'scheduled__2022-05-03T00:00:00+00:00', '--job-id', '578', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmp16bwuzcg', '--error-file', '/tmp/tmp2srchjbo']
[2022-09-06T15:07:52.939+0000] {standard_task_runner.py:80} INFO - Job 578: Subtask postgres_to_s3
[2022-09-06T15:07:53.072+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-03T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T15:07:53.250+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v02
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-03T00:00:00+00:00
[2022-09-06T15:07:53.607+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-06T15:07:55.321+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T15:07:55.758+0000] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hooks.py", line 23, in postgres_to_s3
    (ds_nodash,next_ds_nodash))
psycopg2.errors.UndefinedColumn: column "dat" does not exist
LINE 1: select * from orders where date >= '20220503' and dat < '202...
                                                          ^
HINT:  Perhaps you meant to reference the column "orders.date".

[2022-09-06T15:07:55.789+0000] {taskinstance.py:1412} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v02, task_id=postgres_to_s3, execution_date=20220503T000000, start_date=20220906T150752, end_date=20220906T150755
[2022-09-06T15:07:55.849+0000] {standard_task_runner.py:97} ERROR - Failed to execute job 578 for task postgres_to_s3 (column "dat" does not exist
LINE 1: select * from orders where date >= '20220503' and dat < '202...
                                                          ^
HINT:  Perhaps you meant to reference the column "orders.date".
; 1068)
[2022-09-06T15:07:55.884+0000] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-09-06T15:07:56.003+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-06T15:09:07.616+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-03T00:00:00+00:00 [queued]>
[2022-09-06T15:09:07.640+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-03T00:00:00+00:00 [queued]>
[2022-09-06T15:09:07.641+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:09:07.641+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-06T15:09:07.641+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-06T15:09:07.678+0000] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2022-05-03 00:00:00+00:00
[2022-09-06T15:09:07.688+0000] {standard_task_runner.py:52} INFO - Started process 1153 to run task
[2022-09-06T15:09:07.693+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v02', 'postgres_to_s3', 'scheduled__2022-05-03T00:00:00+00:00', '--job-id', '594', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hooks.py', '--cfg-path', '/tmp/tmpt8dq7iab', '--error-file', '/tmp/tmpclqv4r2n']
[2022-09-06T15:09:07.694+0000] {standard_task_runner.py:80} INFO - Job 594: Subtask postgres_to_s3
[2022-09-06T15:09:07.837+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_hooks_v02.postgres_to_s3 scheduled__2022-05-03T00:00:00+00:00 [running]> on host 45495cb94d52
[2022-09-06T15:09:07.980+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=James
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v02
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2022-05-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-03T00:00:00+00:00
[2022-09-06T15:09:07.982+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-09-06T15:09:08.002+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-06T15:09:08.013+0000] {dag_with_postgres_hooks.py:30} INFO - save orders data in text file dags/get_orders_20220503.txt
[2022-09-06T15:09:08.014+0000] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06T15:09:08.042+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_hooks_v02, task_id=postgres_to_s3, execution_date=20220503T000000, start_date=20220906T150907, end_date=20220906T150908
[2022-09-06T15:09:08.076+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06T15:09:08.128+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
