[2022-09-05T20:56:15.099+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-09-05T20:56:13.598484+00:00 [queued]>
[2022-09-05T20:56:15.112+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-09-05T20:56:13.598484+00:00 [queued]>
[2022-09-05T20:56:15.113+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T20:56:15.113+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-05T20:56:15.113+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T20:56:15.131+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-09-05 20:56:13.598484+00:00
[2022-09-05T20:56:15.136+0000] {standard_task_runner.py:52} INFO - Started process 11369 to run task
[2022-09-05T20:56:15.138+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2022-09-05T20:56:13.598484+00:00', '--job-id', '386', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmp6j_oq6ya', '--error-file', '/tmp/tmpz8fl2pnd']
[2022-09-05T20:56:15.139+0000] {standard_task_runner.py:80} INFO - Job 386: Subtask create_postgres_table
[2022-09-05T20:56:15.217+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-09-05T20:56:13.598484+00:00 [running]> on host c033faf33c57
[2022-09-05T20:56:15.307+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T20:56:13.598484+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-05T20:56:13.598484+00:00
[2022-09-05T20:56:15.319+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T20:56:15.324+0000] {sql.py:315} INFO - Running statement: create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            ), parameters: None
[2022-09-05T20:56:15.434+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20220905T205613, start_date=20220905T205615, end_date=20220905T205615
[2022-09-05T20:56:15.476+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T20:56:15.519+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
