[2022-09-05T21:04:59.605+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05T21:04:59.628+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2022-09-01T00:00:00+00:00 [queued]>
[2022-09-05T21:04:59.629+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:04:59.629+0000] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-09-05T21:04:59.629+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:04:59.658+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-09-01 00:00:00+00:00
[2022-09-05T21:04:59.668+0000] {standard_task_runner.py:52} INFO - Started process 11788 to run task
[2022-09-05T21:04:59.671+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'create_postgres_table', 'scheduled__2022-09-01T00:00:00+00:00', '--job-id', '401', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmpftflrhab', '--error-file', '/tmp/tmphuz425u1']
[2022-09-05T21:04:59.672+0000] {standard_task_runner.py:80} INFO - Job 401: Subtask create_postgres_table
[2022-09-05T21:04:59.775+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v03.create_postgres_table scheduled__2022-09-01T00:00:00+00:00 [running]> on host c033faf33c57
[2022-09-05T21:04:59.944+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v03
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-01T00:00:00+00:00
[2022-09-05T21:04:59.969+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T21:04:59.979+0000] {sql.py:315} INFO - Running statement: create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            ), parameters: None
[2022-09-05T21:04:59.981+0000] {postgres.py:94} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-09-05T21:05:00.008+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v03, task_id=create_postgres_table, execution_date=20220901T000000, start_date=20220905T210459, end_date=20220905T210500
[2022-09-05T21:05:00.057+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T21:05:00.130+0000] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
