[2022-09-05T21:00:11.250+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-09-05T20:55:08.980465+00:00 [queued]>
[2022-09-05T21:00:11.268+0000] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-09-05T20:55:08.980465+00:00 [queued]>
[2022-09-05T21:00:11.269+0000] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:00:11.269+0000] {taskinstance.py:1369} INFO - Starting attempt 2 of 6
[2022-09-05T21:00:11.269+0000] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-05T21:00:11.289+0000] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-09-05 20:55:08.980465+00:00
[2022-09-05T21:00:11.294+0000] {standard_task_runner.py:52} INFO - Started process 11557 to run task
[2022-09-05T21:00:11.298+0000] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2022-09-05T20:55:08.980465+00:00', '--job-id', '392', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operators.py', '--cfg-path', '/tmp/tmpl1woc3pv', '--error-file', '/tmp/tmpge4r7uej']
[2022-09-05T21:00:11.299+0000] {standard_task_runner.py:80} INFO - Job 392: Subtask create_postgres_table
[2022-09-05T21:00:11.396+0000] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-09-05T20:55:08.980465+00:00 [running]> on host c033faf33c57
[2022-09-05T21:00:11.507+0000] {taskinstance.py:1583} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Ancordss
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T20:55:08.980465+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-05T20:55:08.980465+00:00
[2022-09-05T21:00:11.521+0000] {base.py:68} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-09-05T21:00:11.527+0000] {sql.py:315} INFO - Running statement: create table if not exists dag_runs (
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            ), parameters: None
[2022-09-05T21:00:11.528+0000] {postgres.py:94} INFO - NOTICE:  relation "dag_runs" already exists, skipping

[2022-09-05T21:00:11.548+0000] {taskinstance.py:1412} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20220905T205508, start_date=20220905T210011, end_date=20220905T210011
[2022-09-05T21:00:11.596+0000] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05T21:00:11.640+0000] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
